name: Publish

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 8 * * *'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.69.2' # 0.62.0

    - name: Build
      run: hugo -D --disableFastRender

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.pratelli1991.it
        FTP_USERNAME: bbtdbqnt
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./public/
        REMOTE_DIR:  /public_html/
        ARGS: --delete # will delete files on the server if you've deleted them in git

